//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRibbon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelRibbon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Button #1.
        /// </summary>
        internal static string AppLaunchButton1_Label {
            get {
                return ResourceManager.GetString("AppLaunchButton1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First CustomButton.
        /// </summary>
        internal static string AppLaunchButton1_ScreenTip {
            get {
                return ResourceManager.GetString("AppLaunchButton1_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First example of a dynamically registered button..
        /// </summary>
        internal static string AppLaunchButton1_SuperTip {
            get {
                return ResourceManager.GetString("AppLaunchButton1_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Custom Button.
        /// </summary>
        internal static string AppLaunchButton2_Label {
            get {
                return ResourceManager.GetString("AppLaunchButton2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Custom Button.
        /// </summary>
        internal static string AppLaunchButton3_Label {
            get {
                return ResourceManager.GetString("AppLaunchButton3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGSolutions Ribbon.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGSolutions .
        /// </summary>
        internal static string BrandingButton_Label {
            get {
                return ResourceManager.GetString("BrandingButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty (Darn) Good Solutions.
        /// </summary>
        internal static string BrandingButton_ScreenTip {
            get {
                return ResourceManager.GetString("BrandingButton_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple robust solutions to complex problems, by Pieter Geerkens
        ///
        ///https://github.com/pgeerkens/RibbonDispatcher.
        /// </summary>
        internal static string BrandingButton_SuperTip {
            get {
                return ResourceManager.GetString("BrandingButton_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGSolutions.
        /// </summary>
        internal static string BrandingGroup_Label {
            get {
                return ResourceManager.GetString("BrandingGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Current.
        /// </summary>
        internal static string CurrentProjectButtonMS_Label {
            get {
                return ResourceManager.GetString("CurrentProjectButtonMS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VBA from Current Workbook.
        /// </summary>
        internal static string CurrentProjectButtonMS_ScreenTip {
            get {
                return ResourceManager.GetString("CurrentProjectButtonMS_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all VBA code from the current Excel workbook..
        /// </summary>
        internal static string CurrentProjectButtonMS_SuperTip {
            get {
                return ResourceManager.GetString("CurrentProjectButtonMS_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Current.
        /// </summary>
        internal static string CurrentProjectButtonPG_Label {
            get {
                return ResourceManager.GetString("CurrentProjectButtonPG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VBA from Current Workbook.
        /// </summary>
        internal static string CurrentProjectButtonPG_ScreenTip {
            get {
                return ResourceManager.GetString("CurrentProjectButtonPG_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all VBA code from the current Excel workbook..
        /// </summary>
        internal static string CurrentProjectButtonPG_SuperTip {
            get {
                return ResourceManager.GetString("CurrentProjectButtonPG_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Buttons.
        /// </summary>
        internal static string CustomButtonsGroup_Label {
            get {
                return ResourceManager.GetString("CustomButtonsGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable Controls.
        /// </summary>
        internal static string CustomizableGroup_Label {
            get {
                return ResourceManager.GetString("CustomizableGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application-Customizable Controls.
        /// </summary>
        internal static string CustomizableGroup_ScreenTip {
            get {
                return ResourceManager.GetString("CustomizableGroup_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These controls can be dynamically customized, both in behaviour and appearance, within the VBAcode for a workbook. The controls automatically deactivate when a workkbook unaware of the customizations receives focus, and re-activate again when an aware workbook receives focus..
        /// </summary>
        internal static string CustomizableGroup_SuperTip {
            get {
                return ResourceManager.GetString("CustomizableGroup_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Only.
        /// </summary>
        internal static string ImageOnly_Label {
            get {
                return ResourceManager.GetString("ImageOnly_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Image Only.
        /// </summary>
        internal static string ImageOnly_ScreenTip {
            get {
                return ResourceManager.GetString("ImageOnly_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays just the button image when its size is Regular; else both..
        /// </summary>
        internal static string ImageOnly_SuperTip {
            get {
                return ResourceManager.GetString("ImageOnly_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label &amp; Image.
        /// </summary>
        internal static string LabelAndImage_Label {
            get {
                return ResourceManager.GetString("LabelAndImage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Label &amp; Image.
        /// </summary>
        internal static string LabelAndImage_ScreenTip {
            get {
                return ResourceManager.GetString("LabelAndImage_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always displays both the button label and image..
        /// </summary>
        internal static string LabelAndImage_SuperTip {
            get {
                return ResourceManager.GetString("LabelAndImage_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Only.
        /// </summary>
        internal static string LabelOnly_Label {
            get {
                return ResourceManager.GetString("LabelOnly_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Label Only.
        /// </summary>
        internal static string LabelOnly_ScreenTip {
            get {
                return ResourceManager.GetString("LabelOnly_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays just the button label when its size is Regular; else both..
        /// </summary>
        internal static string LabelOnly_SuperTip {
            get {
                return ResourceManager.GetString("LabelOnly_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RD_AboutWindow {
            get {
                object obj = ResourceManager.GetObject("RD_AboutWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright 2018 Pieter Geerkens --&gt;
        ///&lt;!-- When debugging, remember to check: Options -&gt; Advanced -&gt; General -&gt; Show_Add-In_user_interface_errors. --&gt;
        ///&lt;mso:customUI xmlns:mso=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;
        ///              xmlns:rd=&quot;ExcelRibbon&quot;
        ///              onLoad=&quot;OnRibbonLoad&quot; loadImage=&quot;Ribbon_LoadImage&quot;&gt;
        ///  &lt;mso:ribbon&gt;
        ///    &lt;mso:tabs&gt;
        ///        &lt;mso:tab idMso=&quot;TabDeveloper&quot; &gt;
        ///            &lt;mso:group id=&quot;VbaExportGroupMS&quot; getVisible=&quot;ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected.
        /// </summary>
        internal static string SelectedProjectButtonMS_Label {
            get {
                return ResourceManager.GetString("SelectedProjectButtonMS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export from Selected Workbook(s).
        /// </summary>
        internal static string SelectedProjectButtonMS_ScreenTip {
            get {
                return ResourceManager.GetString("SelectedProjectButtonMS_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all VBA code from selected Excel workbook(s)..
        /// </summary>
        internal static string SelectedProjectButtonMS_SuperTip {
            get {
                return ResourceManager.GetString("SelectedProjectButtonMS_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected.
        /// </summary>
        internal static string SelectedProjectButtonPG_Label {
            get {
                return ResourceManager.GetString("SelectedProjectButtonPG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export from Selected Workbook(s).
        /// </summary>
        internal static string SelectedProjectButtonPG_ScreenTip {
            get {
                return ResourceManager.GetString("SelectedProjectButtonPG_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all VBA code from selected Excel workbook(s)..
        /// </summary>
        internal static string SelectedProjectButtonPG_SuperTip {
            get {
                return ResourceManager.GetString("SelectedProjectButtonPG_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Large.
        /// </summary>
        internal static string SizeToggle_AlternateLabel {
            get {
                return ResourceManager.GetString("SizeToggle_AlternateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Small.
        /// </summary>
        internal static string SizeToggle_Label {
            get {
                return ResourceManager.GetString("SizeToggle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles Button Size.
        /// </summary>
        internal static string SizeToggle_ScreenTip {
            get {
                return ResourceManager.GetString("SizeToggle_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles between large and small (preferred size for) buttons for this ribbon group..
        /// </summary>
        internal static string SizeToggle_SuperTIp {
            get {
                return ResourceManager.GetString("SizeToggle_SuperTIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;SRC&apos; folder.
        /// </summary>
        internal static string UseSrcFolderToggleMS_Label {
            get {
                return ResourceManager.GetString("UseSrcFolderToggleMS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles use of folder-name SRC.
        /// </summary>
        internal static string UseSrcFolderToggleMS_ScreenTip {
            get {
                return ResourceManager.GetString("UseSrcFolderToggleMS_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default VBAExport is to a directory &apos;SRC&apos; sibling to the workbook. and Multi-Select is disabled..
        ///
        ///When this toggle is raised the export is instead to a directory eponymous with the workbook, suffixed by VBA. and Multi-Select is enabled..
        /// </summary>
        internal static string UseSrcFolderToggleMS_SuperTip {
            get {
                return ResourceManager.GetString("UseSrcFolderToggleMS_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;SRC&apos; folder.
        /// </summary>
        internal static string UseSrcFolderTogglePG_Label {
            get {
                return ResourceManager.GetString("UseSrcFolderTogglePG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles use of folder-name SRC.
        /// </summary>
        internal static string UseSrcFolderTogglePG_ScreenTip {
            get {
                return ResourceManager.GetString("UseSrcFolderTogglePG_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default VBAExport is to a directory &apos;SRC&apos; sibling to the workbook. and Multi-Select is disabled..
        ///
        ///When this toggle is raised the export is instead to a directory eponymous with the workbook, suffixed by VBA. and Multi-Select is enabled..
        /// </summary>
        internal static string UseSrcFolderTogglePG_SuperTip {
            get {
                return ResourceManager.GetString("UseSrcFolderTogglePG_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA by PGSolutions.
        /// </summary>
        internal static string VbaExportGroupMS_Label {
            get {
                return ResourceManager.GetString("VbaExportGroupMS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA Source Export Controls.
        /// </summary>
        internal static string VbaExportGroupMS_ScreenTip {
            get {
                return ResourceManager.GetString("VbaExportGroupMS_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all VBA code to a sibling direcctory of each workbook, by module type:
        ///
        ///Class modules as .CLS
        ///Standard modules as .VBA
        ///MSForm modules as .FRM
        ///
        ///Project references as .XML.
        /// </summary>
        internal static string VbaExportGroupMS_SuperTip {
            get {
                return ResourceManager.GetString("VbaExportGroupMS_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA Source Code Export.
        /// </summary>
        internal static string VbaExportGroupPG_Label {
            get {
                return ResourceManager.GetString("VbaExportGroupPG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA Source Export Controls.
        /// </summary>
        internal static string VbaExportGroupPG_ScreenTip {
            get {
                return ResourceManager.GetString("VbaExportGroupPG_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all VBA code to a sibling direcctory of each workbook, by module type:
        ///
        ///Class modules as .CLS
        ///Standard modules as .VBA
        ///MSForm modules as .FRM
        ///
        ///Project references as .XML.
        /// </summary>
        internal static string VbaExportGroupPG_SuperTip {
            get {
                return ResourceManager.GetString("VbaExportGroupPG_SuperTip", resourceCulture);
            }
        }
    }
}
