//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRibbon2013.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelRibbon2013.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Button #1.
        /// </summary>
        internal static string AppLaunchButton1_Label {
            get {
                return ResourceManager.GetString("AppLaunchButton1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First CustomButton.
        /// </summary>
        internal static string AppLaunchButton1_ScreenTip {
            get {
                return ResourceManager.GetString("AppLaunchButton1_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First example of a dynamically registered button..
        /// </summary>
        internal static string AppLaunchButton1_SuperTip {
            get {
                return ResourceManager.GetString("AppLaunchButton1_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Custom Button.
        /// </summary>
        internal static string AppLaunchButton2_Label {
            get {
                return ResourceManager.GetString("AppLaunchButton2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Custom Button.
        /// </summary>
        internal static string AppLaunchButton3_Label {
            get {
                return ResourceManager.GetString("AppLaunchButton3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGSolutions Ribbon.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGSolutions.
        /// </summary>
        internal static string BrandingButton_Label {
            get {
                return ResourceManager.GetString("BrandingButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGSolutions.
        /// </summary>
        internal static string BrandingGroup_Label {
            get {
                return ResourceManager.GetString("BrandingGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Buttons.
        /// </summary>
        internal static string CustomButtonsGroup_Label {
            get {
                return ResourceManager.GetString("CustomButtonsGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Only.
        /// </summary>
        internal static string ImageOnly_Label {
            get {
                return ResourceManager.GetString("ImageOnly_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Image Only.
        /// </summary>
        internal static string ImageOnly_ScreenTip {
            get {
                return ResourceManager.GetString("ImageOnly_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays just the button image when its size is Regular; else both..
        /// </summary>
        internal static string ImageOnly_SuperTip {
            get {
                return ResourceManager.GetString("ImageOnly_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label &amp; Image.
        /// </summary>
        internal static string LabelAndImage_Label {
            get {
                return ResourceManager.GetString("LabelAndImage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Label &amp; Image.
        /// </summary>
        internal static string LabelAndImage_ScreenTip {
            get {
                return ResourceManager.GetString("LabelAndImage_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always displays both the button label and image..
        /// </summary>
        internal static string LabelAndImage_SuperTip {
            get {
                return ResourceManager.GetString("LabelAndImage_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Only.
        /// </summary>
        internal static string LabelOnly_Label {
            get {
                return ResourceManager.GetString("LabelOnly_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Label Only.
        /// </summary>
        internal static string LabelOnly_ScreenTip {
            get {
                return ResourceManager.GetString("LabelOnly_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays just the button label when its size is Regular; else both..
        /// </summary>
        internal static string LabelOnly_SuperTip {
            get {
                return ResourceManager.GetString("LabelOnly_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RD_AboutWindow {
            get {
                object obj = ResourceManager.GetObject("RD_AboutWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright 2017 Pieter Geerkens --&gt;
        ///&lt;!-- When debugging, remember to check: Options -&gt; Advanced -&gt; General -&gt; Show_Add-In_user_interface_errors. --&gt;
        ///&lt;mso:customUI xmlns:mso=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;
        ///              xmlns:rd=&quot;ExcelRibbon2013&quot;
        ///              onLoad=&quot;OnRibbonLoad&quot; loadImage=&quot;Ribbon_LoadImage&quot;&gt;
        ///  &lt;mso:ribbon&gt;
        ///    &lt;mso:tabs&gt;
        ///      &lt;mso:tab idQ=&quot;rd:TabPGSolutions&quot; label=&quot;PGSolutions&quot; &gt;
        ///        &lt;mso:group id=&quot;BrandingGro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced Controls.
        /// </summary>
        internal static string ShowAdvancedToggle_Label {
            get {
                return ResourceManager.GetString("ShowAdvancedToggle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced Controls.
        /// </summary>
        internal static string ShowAdvancedToggle_ScreenTip {
            get {
                return ResourceManager.GetString("ShowAdvancedToggle_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles display of the advanced controls.
        /// </summary>
        internal static string ShowAdvancedToggle_SuperTip {
            get {
                return ResourceManager.GetString("ShowAdvancedToggle_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Large.
        /// </summary>
        internal static string SizeToggle_AlternateLabel {
            get {
                return ResourceManager.GetString("SizeToggle_AlternateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Small.
        /// </summary>
        internal static string SizeToggle_Label {
            get {
                return ResourceManager.GetString("SizeToggle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles Button Size.
        /// </summary>
        internal static string SizeToggle_ScreenTip {
            get {
                return ResourceManager.GetString("SizeToggle_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles between large and small (preferred size for) buttons for this ribbon group..
        /// </summary>
        internal static string SizeToggle_SuperTIp {
            get {
                return ResourceManager.GetString("SizeToggle_SuperTIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button #1.
        /// </summary>
        internal static string StandardButton1_Label {
            get {
                return ResourceManager.GetString("StandardButton1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Standard Button.
        /// </summary>
        internal static string StandardButton1_ScreenTip {
            get {
                return ResourceManager.GetString("StandardButton1_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstration of a &quot;standard button&quot;; one that is always visible on the ribbon..
        /// </summary>
        internal static string StandardButton1_SuperTip {
            get {
                return ResourceManager.GetString("StandardButton1_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button #2.
        /// </summary>
        internal static string StandardButton2_Label {
            get {
                return ResourceManager.GetString("StandardButton2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Standard Button.
        /// </summary>
        internal static string StandardButton2_ScreenTip {
            get {
                return ResourceManager.GetString("StandardButton2_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another demonstration of a &quot;standard button&quot;; one that is always visible on the ribbon..
        /// </summary>
        internal static string StandardButton2_SuperTIp {
            get {
                return ResourceManager.GetString("StandardButton2_SuperTIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Buttons.
        /// </summary>
        internal static string StandardButtonsGroup_Label {
            get {
                return ResourceManager.GetString("StandardButtonsGroup_Label", resourceCulture);
            }
        }
    }
}
